

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 556)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(34, 34, 46);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 411, 41))
        self.frame.setStyleSheet("border: 1px solid #00aeff;\n"
"border-radius: 5;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("color: white\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.botmsg_1 = QtWidgets.QLabel(self.centralwidget)
        self.botmsg_1.setGeometry(QtCore.QRect(10, 60, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botmsg_1.setFont(font)
        self.botmsg_1.setStyleSheet("color: white\n"
"")
        self.botmsg_1.setObjectName("botmsg_1")
        self.usermsg_1 = QtWidgets.QLabel(self.centralwidget)
        self.usermsg_1.setGeometry(QtCore.QRect(10, 110, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.usermsg_1.setFont(font)
        self.usermsg_1.setStyleSheet("color: white")
        self.usermsg_1.setScaledContents(False)
        self.usermsg_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usermsg_1.setObjectName("usermsg_1")
        self.botmsg_2 = QtWidgets.QLabel(self.centralwidget)
        self.botmsg_2.setGeometry(QtCore.QRect(10, 160, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botmsg_2.setFont(font)
        self.botmsg_2.setStyleSheet("color: white")
        self.botmsg_2.setObjectName("botmsg_2")
        self.usermsg_2 = QtWidgets.QLabel(self.centralwidget)
        self.usermsg_2.setGeometry(QtCore.QRect(10, 210, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.usermsg_2.setFont(font)
        self.usermsg_2.setStyleSheet("color: white")
        self.usermsg_2.setScaledContents(False)
        self.usermsg_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usermsg_2.setObjectName("usermsg_2")
        self.botmsg_3 = QtWidgets.QLabel(self.centralwidget)
        self.botmsg_3.setGeometry(QtCore.QRect(10, 260, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botmsg_3.setFont(font)
        self.botmsg_3.setStyleSheet("color: white")
        self.botmsg_3.setObjectName("botmsg_3")
        self.usermsg_3 = QtWidgets.QLabel(self.centralwidget)
        self.usermsg_3.setGeometry(QtCore.QRect(10, 310, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.usermsg_3.setFont(font)
        self.usermsg_3.setStyleSheet("color: white")
        self.usermsg_3.setScaledContents(False)
        self.usermsg_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usermsg_3.setObjectName("usermsg_3")
        self.botmsg_4 = QtWidgets.QLabel(self.centralwidget)
        self.botmsg_4.setGeometry(QtCore.QRect(10, 360, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botmsg_4.setFont(font)
        self.botmsg_4.setStyleSheet("color: white")
        self.botmsg_4.setObjectName("botmsg_4")
        self.usermsg_4 = QtWidgets.QLabel(self.centralwidget)
        self.usermsg_4.setGeometry(QtCore.QRect(10, 410, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.usermsg_4.setFont(font)
        self.usermsg_4.setStyleSheet("color: white")
        self.usermsg_4.setScaledContents(False)
        self.usermsg_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usermsg_4.setObjectName("usermsg_4")
        self.botmsg_5 = QtWidgets.QLabel(self.centralwidget)
        self.botmsg_5.setGeometry(QtCore.QRect(10, 460, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botmsg_5.setFont(font)
        self.botmsg_5.setStyleSheet("color: white")
        self.botmsg_5.setObjectName("botmsg_5")
        self.usermsg_5 = QtWidgets.QLabel(self.centralwidget)
        self.usermsg_5.setGeometry(QtCore.QRect(10, 510, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.usermsg_5.setFont(font)
        self.usermsg_5.setStyleSheet("color: white")
        self.usermsg_5.setScaledContents(False)
        self.usermsg_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usermsg_5.setObjectName("usermsg_5")
        self.usermsg_1.raise_()
        self.frame.raise_()
        self.botmsg_1.raise_()
        self.botmsg_2.raise_()
        self.usermsg_2.raise_()
        self.botmsg_3.raise_()
        self.usermsg_3.raise_()
        self.botmsg_4.raise_()
        self.usermsg_4.raise_()
        self.botmsg_5.raise_()
        self.usermsg_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ФРИСТИ V1.0"))
        self.botmsg_1.setText(_translate("MainWindow", "-"))
        self.usermsg_1.setText(_translate("MainWindow", "-"))
        self.botmsg_2.setText(_translate("MainWindow", "-"))
        self.usermsg_2.setText(_translate("MainWindow", "-"))
        self.botmsg_3.setText(_translate("MainWindow", "-"))
        self.usermsg_3.setText(_translate("MainWindow", "-"))
        self.botmsg_4.setText(_translate("MainWindow", "-"))
        self.usermsg_4.setText(_translate("MainWindow", "-"))
        self.botmsg_5.setText(_translate("MainWindow", "-"))
        self.usermsg_5.setText(_translate("MainWindow", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
